### ISSUE TITLE
検索APIの追加

### ISSUE THREAD

**Issue by tejima** [houou/api.php#1]
ドキュメントから先につくっていったほうがいいかも。
エントリポイントは潔く
api.php/search.json

リクエスト
・apiKey
・word
・limit
・detail=1 モデルのディテールを含むか？
その他オプション

レスポンス
ModelType:Diary ActivityDataなど
id:プライマリーキー
summary:検索結果のサマリ１００〜１４０文字程度
url:検索結果の実体にアクセスするためのURL
model_detail: データの実体 detailオプションが付いたときのみ表示

**Comment by upsilon** [comment]
98f42680e349ec22d6d36018edaaf98ce35cc558 にて追加しました（サンプル未作成）。

**Comment by tejima** [comment]
閉じます。以降本プロジェクトはドキュメントサイトになる。
